#!/bin/sh

exec >/dev/null 2>&1

swaybg -i $(xdg-user-dir PICTURES)/wallpapers/the-ninth-wave-gruvbox.jpg &
mako &
makoctl mode -s labwc
emacs --daemon &
wl-paste --watch cliphist store &
ydotoold &
mpdris2-rs &
playerctld daemon &
#xfce4-panel &
labwc-watch-kbd-layout &
i3status | labline -f 'UbuntuMono Nerd Font 12' &
